### ISSUE TITLE
configure HDF5 with CMake intead of configure

### ISSUE THREAD

**Issue by untereiner** [GEOS-DEV/thirdPartyLibs#211]
Hi,
When using configure/make the cmake configuration files are not installed (HDF5config.cmake and HDF5options.cmake).
Thus, a cmakefile relying completelly on FindHDF5.cmake and HDF5_ROOT or HDF5_DIR will fail to find the TPL one.
It will possibly find a hdf5 already installed on the system because h5cc or h5pcc from the system is called.

**Comment by TotoGaz** [comment]
What are the ways to get the cmake configuration files installed?
Build using `cmake`?

**Comment by untereiner** [comment]
I think the only way is to build with cmake. I did find a way using autotools
